---
- name: ppa apt-key
  apt_key: id=7B2C3B0889BF5709A105D03AC2518248EEA14886 keyserver=keyserver.ubuntu.com
- name: ppa apt
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"
- name: accept oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
- name: java7 installer
  apt: pkg=oracle-java7-installer update_cache=yes
